version: '3.8'
services:
  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  # Database postgresql
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=diluprod21db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Controwell.2020
    container_name: postgres_db
    ports:
      - "5432:5432"
  
  # PgAdmin4
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    container_name: pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - "db"


  # Django App
  app:
    build: .
    volumes:
      - .:/diluprod21
    environment:
      - DATABASE_URL=postgres://root:Controwell.2020@db:5432/diluprod21db
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@mycomany.com
      - REDIS_TLS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    image: app:diluprod21
    container_name: diluprod21_container
    command: >
      sh -c "python manage.py waitdb --seconds 15 &&
             python manage.py migrate &&
             python manage.py createsuperuser --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - "db"
  
  # Celery
  celery:
    restart: always
    build: 
      context: .
    command: celery -A diluprod21 worker -l INFO #se usa pq el entorno es linux, para windows: celery -A diluprod21 worker -l info --pool=solo
    volumes:
      - .:/diluprod21
    environment:
      - DATABASE_URL=postgres://root:Controwell.2020@db:5432/diluprod21db
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - C_FORCE_ROOT="true"
      - REDIS_TLS_URL=redis://redis:6379
    container_name: celery
    depends_on:
      - "db"
      - "redis"
      - "app"