# Generated by Django 3.1.7 on 2021-06-09 05:01

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('bsw', models.DecimalField(decimal_places=2, max_digits=7)),
                ('api', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tasaLiquido', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tasaGas', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tasaAgua', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tasaAceite', models.DecimalField(decimal_places=2, max_digits=11)),
                ('gor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('thp', models.DecimalField(decimal_places=2, max_digits=11)),
                ('velocidadBomba', models.DecimalField(decimal_places=2, max_digits=7)),
                ('corrienteVSD', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pip', models.DecimalField(decimal_places=2, max_digits=11)),
                ('voltajeOutVSD', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tempCabeza', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pruebaValida', models.CharField(choices=[('VALIDA', 'Valida'), ('PENDIE', 'Pendiente')], default='VALIDA', max_length=6)),
                ('comentarios', models.TextField()),
                ('salinidad', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=6)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=6)),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DataStork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidorNo', models.IntegerField(blank=True)),
                ('noWell', models.CharField(blank=True, max_length=20)),
                ('swMezcla', models.DecimalField(blank=True, decimal_places=2, max_digits=11)),
                ('diluyenteInyectado', models.DecimalField(blank=True, decimal_places=2, max_digits=11)),
                ('comentarios', models.TextField(blank=True)),
                ('dataAVM', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='storkAVM', to='Basic.dataavm')),
            ],
        ),
        migrations.AddField(
            model_name='dataavm',
            name='pozo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic.pozo'),
        ),
        migrations.CreateModel(
            name='DataAgar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidorNo', models.IntegerField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('dataAVM', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agarAVM', to='Basic.dataavm')),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pozos', models.ManyToManyField(blank=True, related_name='ListaPozos', to='Basic.Pozo')),
            ],
        ),
    ]
