# Generated by Django 3.1.7 on 2021-06-09 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataagar',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataagar',
            name='dataAVM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agarAVM', to='Basic.dataavm'),
        ),
        migrations.AlterField(
            model_name='dataagar',
            name='medidorNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datastork',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datastork',
            name='dataAVM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storkAVM', to='Basic.dataavm'),
        ),
        migrations.AlterField(
            model_name='datastork',
            name='diluyenteInyectado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='datastork',
            name='medidorNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datastork',
            name='noWell',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datastork',
            name='swMezcla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
    ]
