# Generated by Django 3.1.7 on 2021-08-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskTracker',
            fields=[
                ('task', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('FINISHED', 'FINISHED'), ('WORKING', 'WORKING'), ('FAILED', 'FAILED')], default='FINISHED', max_length=12)),
                ('type_error', models.TextField(blank=True)),
            ],
        ),
    ]
