# Generated by Django 3.1.7 on 2021-06-08 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('bsw', models.DecimalField(decimal_places=2, max_digits=7)),
                ('api', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tasaLiquido', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tasaGas', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tasaAgua', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tasaAceite', models.DecimalField(decimal_places=2, max_digits=11)),
                ('gor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('thp', models.DecimalField(decimal_places=2, max_digits=11)),
                ('velocidadBomba', models.DecimalField(decimal_places=2, max_digits=7)),
                ('corrienteVSD', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pip', models.DecimalField(decimal_places=2, max_digits=11)),
                ('voltajeOutVSD', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tempCabeza', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pruebaValida', models.CharField(choices=[('VALIDA', 'Valida'), ('PENDIE', 'Pendiente')], default='VALIDA', max_length=6)),
                ('comentarios', models.TextField()),
                ('salinidad', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=6)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=6)),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DataStork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidorNo', models.IntegerField(blank=True)),
                ('noWell', models.CharField(blank=True, max_length=20)),
                ('swMezcla', models.DecimalField(blank=True, decimal_places=2, max_digits=11)),
                ('diluyenteInyectado', models.DecimalField(blank=True, decimal_places=2, max_digits=11)),
                ('comentarios', models.TextField(blank=True)),
                ('dataAVM', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='storkAVM', to='Basic.dataavm')),
            ],
        ),
        migrations.AddField(
            model_name='dataavm',
            name='pozo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic.pozo'),
        ),
        migrations.CreateModel(
            name='DataAgar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.IntegerField(blank=True)),
                ('dataAVM', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agarAVM', to='Basic.dataavm')),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pozos', models.ManyToManyField(blank=True, related_name='ListaPozos', to='Basic.Pozo')),
            ],
        ),
    ]
