# Generated by Django 3.1.7 on 2021-06-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0002_auto_20210622_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataavm',
            options={'get_latest_by': 'fecha', 'ordering': ['fecha']},
        ),
    ]
