# Generated by Django 3.1.7 on 2021-06-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0002_auto_20210609_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8),
        ),
    ]
