# Generated by Django 3.1.7 on 2021-06-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0002_auto_20210607_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozo',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6),
        ),
    ]
