# Generated by Django 3.1.7 on 2021-06-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0003_auto_20210607_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataagar',
            old_name='reporte',
            new_name='medidorNo',
        ),
        migrations.AddField(
            model_name='dataagar',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
    ]
