# Generated by Django 3.1.7 on 2021-06-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0004_auto_20210625_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataavm',
            name='voltajeOutVSD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voltaje'),
        ),
    ]
