# Generated by Django 3.1.7 on 2021-10-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0004_datastork_fluidototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastork',
            name='bsw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
        ),
    ]
