# Generated by Django 3.1.7 on 2021-10-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0005_datastork_bsw'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastork',
            name='api',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
