# Generated by Django 3.1.7 on 2021-07-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0005_auto_20210625_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataavm',
            name='pruebaValida',
            field=models.CharField(choices=[('VALIDA', 'Valida'), ('PENDIENTE', 'Pendiente')], default='VALIDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataavm',
            name='velocidadBomba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dataavm',
            name='voltajeOutVSD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
