# Generated by Django 3.1.7 on 2021-06-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0005_auto_20210610_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataavm',
            name='api',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='bsw',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='corrienteVSD',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='gor',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='pip',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='pruebaValida',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='salinidad',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='tasaAceite',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='tasaAgua',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='tasaGas',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='tasaLiquido',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='tempCabeza',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='thp',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='velocidadBomba',
        ),
        migrations.RemoveField(
            model_name='dataavm',
            name='voltajeOutVSD',
        ),
    ]
