# Generated by Django 3.1.7 on 2021-10-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0006_datastork_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastork',
            old_name='api',
            new_name='apiMezcla',
        ),
    ]
