# Generated by Django 3.1.7 on 2021-11-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0007_auto_20211006_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='PozoInyector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caudalInyeccion', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('fechaInicio', models.DateField()),
                ('proceso', models.CharField(choices=[('Inyección de agua', 'Inyección de agua'), ('Inyección de polímero', 'Inyección de polímero')], default='Inyección de agua', max_length=25)),
                ('pozoAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PozoAsociado', to='Basic.pozo')),
                ('pozoInyector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PozoInyector', to='Basic.pozo')),
            ],
        ),
        migrations.DeleteModel(
            name='DataAgar',
        ),
    ]
