# Generated by Django 3.1.7 on 2021-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0008_auto_20211109_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pozoinyector',
            name='pozoAsociado',
        ),
        migrations.AddField(
            model_name='pozoinyector',
            name='pozosAsociados',
            field=models.ManyToManyField(blank=True, related_name='PozosAsociados', to='Basic.Pozo'),
        ),
    ]
