# Generated by Django 3.1.7 on 2021-11-10 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0011_auto_20211109_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idMuestra', models.CharField(max_length=25)),
                ('tipoMuestra', models.CharField(blank=True, max_length=25, null=True)),
                ('bsw', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('api', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('cloruros', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PozoLaboratorio', to='Basic.pozo')),
            ],
        ),
    ]
